# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043b\u043e\u0432\u043e\u043a \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f')),
                ('text_message', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f')),
                ('mailing_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
                ('status', models.CharField(choices=[('\u0412\u042b\u041f\u041e\u041b\u041d\u0415\u041d\u041e', '\u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e'), ('\u041e\u0411\u0420\u0410\u0411\u041e\u0422\u041a\u0410', '\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0430'), ('\u0421\u041e\u0417\u0414\u0410\u041d\u041e', '\u0421\u043e\u0437\u0434\u0430\u043d\u043e')], default='\u0421\u041e\u0417\u0414\u0410\u041d\u041e', max_length=10)),
                ('subscribers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsribers', to='Mailings.Subscribers', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438')),
            ],
        ),
    ]
