# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0002_mailing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='mailing',
            name='subscribers',
            field=models.ManyToManyField(related_name='subsribers', to='Mailings.Subscribers', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438'),
        ),
    ]
