# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0003_auto_20221123_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='taskid',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_date',
            field=models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438'),
        ),
    ]
