# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0004_auto_20221123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='taskid',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
