# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0005_auto_20221123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('CREATED', 'Created')], default='\u0421\u041e\u0417\u0414\u0410\u041d\u041e', max_length=10),
        ),
    ]
