# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-23 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mailings', '0006_auto_20221123_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('NOT OPEN', 'Not open')], default='NOT_OPEN', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('CREATED', 'Created')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='taskid',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailing_message',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Mailings.Mailing', verbose_name='\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='mailing_message',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='Mailings.Subscribers', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a'),
        ),
    ]
